# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 05:51
from __future__ import unicode_literals

import apps.member.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Physic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.CharField(max_length=5)),
                ('body_height', models.CharField(max_length=5)),
                ('arm_span', models.CharField(max_length=5)),
                ('full_draw', models.CharField(max_length=5)),
                ('over_draw', models.CharField(max_length=5)),
                ('hospital_history', models.TextField()),
                ('blood_group', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'physic',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=25)),
                ('born_place', models.CharField(max_length=100)),
                ('born_date', models.DateField()),
                ('religion', models.CharField(blank=True, default='Islam', max_length=100)),
                ('identity_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('picture', versatileimagefield.fields.VersatileImageField(upload_to=apps.member.models.profile_picture)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='division.Level')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='organization.Organization')),
                ('physic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Physic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
